# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 801)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 10, 341, 291))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 310, 341, 271))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_action_cite_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_action_cite_1.setGeometry(QtCore.QRect(640, 110, 391, 28))
        self.pushButton_action_cite_1.setObjectName("pushButton_action_cite_1")
        self.pushButton_left1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_left1.setGeometry(QtCore.QRect(390, 10, 41, 291))
        self.pushButton_left1.setObjectName("pushButton_left1")
        self.pushButton_left2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_left2.setGeometry(QtCore.QRect(390, 310, 41, 271))
        self.pushButton_left2.setObjectName("pushButton_left2")
        self.pushButton_action_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_action_5.setGeometry(QtCore.QRect(640, 170, 191, 28))
        self.pushButton_action_5.setObjectName("pushButton_action_5")
        self.pushButton_action_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_action_1.setGeometry(QtCore.QRect(440, 110, 191, 28))
        self.pushButton_action_1.setObjectName("pushButton_action_1")
        self.pushButton_action_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_action_2.setGeometry(QtCore.QRect(440, 140, 191, 28))
        self.pushButton_action_2.setObjectName("pushButton_action_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(440, 30, 231, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_1.setGeometry(QtCore.QRect(440, 10, 211, 31))
        self.checkBox_1.setObjectName("checkBox_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 510, 171, 21))
        self.label.setObjectName("label")
        self.pushButton_action_last = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_action_last.setGeometry(QtCore.QRect(440, 530, 591, 51))
        self.pushButton_action_last.setObjectName("pushButton_action_last")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 70, 641, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 31, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 310, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 580, 181, 21))
        self.label_5.setObjectName("label_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 610, 341, 101))
        self.textEdit_3.setObjectName("textEdit_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(440, 50, 151, 31))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_action_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_action_6.setGeometry(QtCore.QRect(840, 170, 191, 28))
        self.pushButton_action_6.setObjectName("pushButton_action_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 490, 641, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(440, 90, 361, 21))
        self.label_8.setObjectName("label_8")
        self.pushButton_left3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_left3.setGeometry(QtCore.QRect(390, 610, 41, 101))
        self.pushButton_left3.setObjectName("pushButton_left3")
        self.pushButton_action_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_action_3.setGeometry(QtCore.QRect(440, 170, 191, 28))
        self.pushButton_action_3.setObjectName("pushButton_action_3")
        self.pushButton_remember_setting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remember_setting.setGeometry(QtCore.QRect(660, 17, 371, 51))
        self.pushButton_remember_setting.setObjectName("pushButton_remember_setting")
        self.pushButton_action_cite_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_action_cite_3.setGeometry(QtCore.QRect(640, 140, 391, 28))
        self.pushButton_action_cite_3.setObjectName("pushButton_action_cite_3")
        self.pushButton_action_remove_empty = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_action_remove_empty.setGeometry(QtCore.QRect(440, 200, 191, 28))
        self.pushButton_action_remove_empty.setObjectName("pushButton_action_remove_empty")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(440, 240, 160, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEdit_replace_text_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_replace_text_1.setText("")
        self.lineEdit_replace_text_1.setObjectName("lineEdit_replace_text_1")
        self.verticalLayout.addWidget(self.lineEdit_replace_text_1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.lineEdit_replace_text_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_replace_text_2.setText("")
        self.lineEdit_replace_text_2.setObjectName("lineEdit_replace_text_2")
        self.verticalLayout.addWidget(self.lineEdit_replace_text_2)
        self.pushButton_replace = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.verticalLayout.addWidget(self.pushButton_replace)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(610, 240, 181, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_add_fix_text = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_add_fix_text.setText("")
        self.lineEdit_add_fix_text.setObjectName("lineEdit_add_fix_text")
        self.verticalLayout_2.addWidget(self.lineEdit_add_fix_text)
        self.pushButton_add_fix_text = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_add_fix_text.setObjectName("pushButton_add_fix_text")
        self.verticalLayout_2.addWidget(self.pushButton_add_fix_text)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(610, 310, 181, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_save_first_text = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_save_first_text.setText("")
        self.lineEdit_save_first_text.setObjectName("lineEdit_save_first_text")
        self.verticalLayout_3.addWidget(self.lineEdit_save_first_text)
        self.pushButton_save_first_text = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_save_first_text.setObjectName("pushButton_save_first_text")
        self.verticalLayout_3.addWidget(self.pushButton_save_first_text)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(800, 240, 220, 73))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.lineEdit_split_by_these = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_split_by_these.setText("")
        self.lineEdit_split_by_these.setObjectName("lineEdit_split_by_these")
        self.verticalLayout_4.addWidget(self.lineEdit_split_by_these)
        self.pushButton_split_by_these = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_split_by_these.setObjectName("pushButton_split_by_these")
        self.verticalLayout_4.addWidget(self.pushButton_split_by_these)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_action_cite_1.setText(_translate("MainWindow", "参考文献.多行格式化，“数字”开头或“[数字]”开头"))
        self.pushButton_left1.setText(_translate("MainWindow", "粘贴"))
        self.pushButton_left2.setText(_translate("MainWindow", "复制"))
        self.pushButton_action_5.setText(_translate("MainWindow", "摘要.按分号分隔"))
        self.pushButton_action_1.setText(_translate("MainWindow", "合并行"))
        self.pushButton_action_2.setText(_translate("MainWindow", "合并行后按点分隔"))
        self.checkBox_2.setText(_translate("MainWindow", "自动将框2内容粘贴到剪切板"))
        self.checkBox_1.setText(_translate("MainWindow", "自动将剪切板粘贴到框1"))
        self.label.setText(_translate("MainWindow", "上一次使用："))
        self.pushButton_action_last.setText(_translate("MainWindow", "参考文献.多行格式化"))
        self.label_2.setText(_translate("MainWindow", "======================================================================================================================================"))
        self.label_3.setText(_translate("MainWindow", "框1"))
        self.label_4.setText(_translate("MainWindow", "框2"))
        self.label_5.setText(_translate("MainWindow", "框3，翻译为中文"))
        self.checkBox_3.setText(_translate("MainWindow", "是否翻译框2"))
        self.pushButton_action_6.setText(_translate("MainWindow", "无处理"))
        self.label_7.setText(_translate("MainWindow", "======================================================================================================================================"))
        self.label_8.setText(_translate("MainWindow", "处理框1内容后输出到框2"))
        self.pushButton_left3.setText(_translate("MainWindow", "复制"))
        self.pushButton_action_3.setText(_translate("MainWindow", "去除连续空格"))
        self.pushButton_remember_setting.setText(_translate("MainWindow", "记住这些选项"))
        self.pushButton_action_cite_3.setText(_translate("MainWindow", "参考文献.多行格式化，“[”开头"))
        self.pushButton_action_remove_empty.setText(_translate("MainWindow", "去除空格"))
        self.label_6.setText(_translate("MainWindow", "将"))
        self.label_9.setText(_translate("MainWindow", "替换为"))
        self.pushButton_replace.setText(_translate("MainWindow", "替换"))
        self.pushButton_add_fix_text.setText(_translate("MainWindow", "给头尾加上，并换行"))
        self.pushButton_save_first_text.setText(_translate("MainWindow", "保留前几位字符"))
        self.label_10.setText(_translate("MainWindow", "该框内符号用空格分隔"))
        self.pushButton_split_by_these.setText(_translate("MainWindow", "按这些符号分隔"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))

